include:
  - local: ".gitlab/stages/release.yml"
  # TODO: remove stage after feat-add-python-sdk branch merge. It's only used for testing.
  - local: ".gitlab/stages/documentation.yml"
  - local: ".gitlab/stages/quality.yml"

stages:
  - release
  # TODO: remove stage after feat-add-python-sdk branch merge. It's only used for testing.
  - documentation
  - quality
