[modules]

[modules.python-sdk]
source = "github.com/dagger/python-sdk"

[sdks.python]
module = "python-sdk"

[modules.shiryu]
source = "./"

[sdks.python.scopes."."]
is-module = true
name = "shiryu"
