[project]
name = "shiryu"
dynamic = ["version"]
description = "A SDK for programming languages."
readme = "README.md"
authors = [
  { name = "von Bergen, Federico", email = "federicovonbergen@gmail.com" },
]
classifiers = [
  # "Development Status :: 5 - Production/Stable",
  # "Framework :: AsyncIO",
  # "Framework :: Pytest",
  # "Intended Audience :: Developers",
  # "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Operating System :: OS Independent",
  "Typing :: Typed",
]
# linked to [tool.uv] environments
# python3.10
# - zensical minimum python support - (documenter) - https://github.com/zensical/zensical/blob/v0.0.3/pyproject.toml#L36
# - dagger-io minimum python support - https://pypi.org/project/dagger-io/0.1.1/
# python3.11 - https://docs.python.org/3/whatsnew/3.11.html
# - tomllib: Support for Parsing TOML in the Standard Library
# - Added StrEnum
# python3.12 - https://docs.python.org/3/whatsnew/3.12.html
# - Add pathlib.Path.walk()
# python3.12 - https://docs.python.org/3/whatsnew/3.12.html
# - New type parameter syntax and the type statement
requires-python = ">=3.12"
# Dagger module developments ends up using uv.lock to install module dependencies.
dependencies = [
  # Should be the same version as the dagger.json engineVersion field.
  # >= v0.18.15: New container.Exists and directory. Exists API for testing if a file exists, and optionally type (e.g. file or directory). (https://github.com/dagger/dagger/releases/tag/v0.18.15)
  # <release>
  "dagger-io >= v0.18.15",
  # </release>
  # <develop>
  # "dagger-io",
  # </develop>
  # >= 3.0.0: jinja is usable after version 3.0.0. Before that version throws: `ImportError: cannot import name 'soft_unicode' from 'markupsafe'`
  "jinja2 >= 3.0.0",
  # "setuptools-scm",
]

[build-system]
requires = ["hatchling==1.31.0", "hatch-vcs==0.5.0"]
build-backend = "hatchling.build"

# Dependencies that will be installed for the specific module call.
[dependency-groups]
auditor = ["uv >= 0.11.0"]
builder = ["hatch"]
checker = ["pytest >= 7.4.0", "pytest-asyncio >= 0.24.0", "ty >= 0.0.1-alpha.8"]
documenter = [
  "mkdocs-autorefs",
  "mkdocstrings-python >= 1.11.0",
  "zensical >= 0.0.22",
]
linter = [
  "commit-check >= 2.0.0",
  # https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md#0160
  # >= 0.16.0: New PLR0917 rule
  "ruff >= 0.16.0",
]
tester = [
  "pytest >= 7.4.0",
  "pytest-asyncio >= 0.24.0",
  "pytest-cov >= 2.3.0",
  "pytest-xdist[psutil] >= 1.18.0",
]

[urls]
# "Homepage" = ""
"Documentation" = "https://fvonbergen.github.io/shiryu"
"Repository" = "https://github.com/fvonbergen/shiryu"
"Issues" = "https://github.com/fvonbergen/shiryu/issues"
"Changelog" = "https://github.com/fvonbergen/shiryu/blob/master/CHANGELOG.md"
# "Release Notes" = ""
# "Community" = ""
# "Twitter" = ""

# <develop>
# [tool.uv.sources]
# dagger-io = { path = "sdk", editable = true }
# </develop>

# Build system changed in dagger v0.18.6 (https://github.com/dagger/dagger/releases/tag/sdk%2Fpython%2Fv0.18.16)
# https://github.com/ninoseki/uv-dynamic-versioning/
# uv_build backend does not support a hook for dynamic versioning yet (https://github.com/astral-sh/uv/issues/14561)
#[build-system]
#requires = ["uv_build>=0.8.4,<0.9.0", "uv-dynamic-versioning"]
#build-backend = "uv_build"
#
#[tool.uv-dynamic-versioning]
#fallback-version = "0.0.0"

[tool.uv]
# linked to [project] requires-python
environments = [
  "python_version == '3.12'",
  "python_version == '3.13'",
  "python_version == '3.14'",
]

[tool.hatch.version]
source = "vcs"
fallback-version = "0.0.0+unknown"
