[pytest]
addopts = -vv --cov --cov-report=term --cov-report=xml --cov-config=.coveragerc
python_files = test_*.py
pythonpath = src
testpaths = tests/unit
# pytest-asyncio
asyncio_mode = strict
asyncio_default_fixture_loop_scope = function