
# target-version = "py38"
cache-dir = ".ruff_cache"
respect-gitignore = true

[lint]
select = ["A", "B", "C90", "D", "E", "EM", "F", "I", "N", "PTH", "RUF", "W"]
ignore = ["D203", "D212", "E501"]
# extend-ignore = []

[lint.pydocstyle]
convention = "google"

# [lint.per-file-ignores]
