name: "auditor audit"
description: "Runs auditor audit function on a project"

inputs:
  dagger_cloud_token:
    required: true
    description: "Dagger cloud token"
  shiryu_version:
    required: false
    description: "Shiryu version"
    default: "feat/add-python-sdk-release"
  sdk_language:
    description: "SDK programming language"
    default: "python"
  platform:
    description: "Platform config OS and architecture in a Container"
    default: "linux/amd64"
  project_directory:
    description: "Project directory path."
    default: "."

runs:
  using: "composite"
  steps:
    - id: call_dagger_auditor_audit
      name: Call Dagger Auditor audit
      uses: dagger/dagger-for-github@v8.4.0
      with:
        version: "v0.21.7"
        verb: call
        module: github.com/fvonbergen/shiryu@${{ inputs.shiryu_version }}
        args: ${{ inputs.sdk_language }} auditor audit --platform="${{ inputs.platform }}" --project-directory="${{ inputs.project_directory }}"
        cloud-token: ${{ inputs.dagger_cloud_token }}
