name: "tester unit"
description: "Runs tester unit function on a project"

inputs:
  dagger_cloud_token:
    required: true
    description: "Dagger cloud token"
  shiryu_version:
    required: false
    description: "Shiryu version"
    default: "feat/add-python-sdk-release"
  sdk_language:
    description: "SDK programming language"
    default: "python"
  platform:
    description: "Platform config OS and architecture in a Container"
    default: "linux/amd64"
  privileged_nesting:
    description: "Whether to allow container dagger client to connect to the dagger engine"
    default: "False"
  project_directory:
    description: "Project directory path."
    default: "."

runs:
  using: "composite"
  steps:
    - id: call_dagger_tester_unit
      name: Call Dagger Tester unit
      uses: dagger/dagger-for-github@v8.4.0
      with:
        version: "v0.21.7"
        verb: call
        module: github.com/fvonbergen/shiryu@${{ inputs.shiryu_version }}
        args: ${{ inputs.sdk_language }} tester unit --platform="${{ inputs.platform }}" --privileged-nesting="${{ inputs.privileged_nesting }}" --project-directory="${{ inputs.project_directory }}"
        cloud-token: ${{ inputs.dagger_cloud_token }}
