name: "checker check"
description: "Runs checker check function on a project"

inputs:
  dagger_cloud_token:
    required: true
    description: "Dagger cloud token"
  shiryu_version:
    required: false
    description: "Shiryu version"
    default: "debug-dagger-module-testing-inside-pytest"
  sdk_language:
    description: "SDK programming language"
    default: "python"
  platform:
    description: "Platform config OS and architecture in a Container."
    default: "linux/amd64"
  project:
    description: "Project location"
    default: "."

runs:
  using: "composite"
  steps:
    - id: call_dagger_checker_check
      name: Call Dagger Checker check
      uses: dagger/dagger-for-github@v8.4.0
      with:
        version: "latest"
        verb: call
        module: github.com/fvonbergen/shiryu@${{ inputs.shiryu_version }}
        args: ${{ inputs.sdk_language }} checker check --platform="${{ inputs.platform }}" --project="${{ inputs.project }}"
        cloud-token: ${{ inputs.dagger_cloud_token }}

