name: "builder test"
description: "Runs builder test function on a project"

inputs:
  dagger_cloud_token:
    required: true
    description: "Dagger cloud token"
  shiryu_version:
    required: false
    description: "Shiryu version"
    default: "feat-add-python-sdk"
  sdk_language:
    description: "SDK programming language"
    default: "python"
  platform:
    description: "Platform config OS and architecture in a Container."
    default: "linux/amd64"
  project_directory:
    description: "Project directory path"
    default: "."

runs:
  using: "composite"
  steps:
    - id: call_dagger_builder_test
      name: Call Dagger Builder test
      uses: dagger/dagger-for-github@v8.4.0
      with:
        version: "v0.21.0"
        verb: call
        module: github.com/fvonbergen/shiryu@${{ inputs.shiryu_version }}
        args: ${{ inputs.sdk_language }} builder test --platform="${{ inputs.platform }}" --project-directory="${{ inputs.project_directory }}"
        cloud-token: ${{ inputs.dagger_cloud_token }}
