include:
  - local: ".gitlab/jobs/.dagger.yml"

.auditor_audit:
  extends: .dagger
  variables:
    SHIRYU_VERSION: "feat/add-python-sdk-release-dagger-v1.0.0-beta.16"
    SDK_LANGUAGE: "python"
    PLATFORM: "linux/amd64"
  script:
    - dagger --mod=gitlab.com/fvonbergen1/shiryu@${SHIRYU_VERSION} call ${SDK_LANGUAGE} auditor audit --platform="${PLATFORM}"
