include:
  - local: ".gitlab/jobs/.dagger.yml"

.documenter_document:
  extends: .dagger
  variables:
    SHIRYU_VERSION: "feat-add-python-sdk"
    SDK_LANGUAGE: "python"
    PLATFORM: "linux/amd64"
    PROJECT_DIRECTORY: "."
  script:
    - dagger --mod=gitlab.com/fvonbergen1/shiryu@${SHIRYU_VERSION} call ${SDK_LANGUAGE} documenter document --platform="${PLATFORM}" --project-directory="${PROJECT_DIRECTORY}" export --path=./docs
    - mkdir public
    - cp --recursive docs/build/html/* public/
  artifacts:
    paths:
      - public