include:
  - local: ".gitlab/jobs/.dagger.yml"

.releaser_release:
  extends: .dagger
  variables:
    SHIRYU_VERSION: "feat/add-python-sdk"
    SDK_LANGUAGE: "python"
    PLATFORM: "linux/amd64"
    PROJECT_DIRECTORY: "."
    AUTH_TOKEN: "${GITLAB_TOKEN}"
    GIT_USER_NAME: "${GIT_USER_NAME}"
    GIT_USER_EMAIL: "${GIT_USER_EMAIL}"
  script:
    - dagger --mod=gitlab.com/fvonbergen1/shiryu@${SHIRYU_VERSION} call ${SDK_LANGUAGE} releaser release --platform="${PLATFORM}" --project-directory="${PROJECT_DIRECTORY}" --auth-token="env:AUTH_TOKEN" --git-user-name="${GIT_USER_NAME}" --git-user-email="${GIT_USER_EMAIL}"
  rules:
    - when: manual
