include:
  - local: ".gitlab/jobs/.dagger.yml"

.tester_unit:
  extends: .dagger
  variables:
    SHIRYU_VERSION: "debug-dagger-module-testing-inside-pytest"
    SDK_LANGUAGE: "python"
    PLATFORM: "linux/amd64"
    PROJECT: "."
  script:
    - dagger --mod=gitlab.com/fvonbergen1/shiryu@${SHIRYU_VERSION} call ${SDK_LANGUAGE} tester unit --platform="${PLATFORM}" --project="${PROJECT}" --experimental-privileged-nesting=True
