"""Render a module description as a static Dang entrypoint."""

from __future__ import annotations

import json
import pathlib
from collections.abc import Iterator

from dagger.mod._describe import (
    ArgumentDescription,
    EnumDescription,
    FunctionDescription,
    ModuleDescription,
    ObjectDescription,
    TypeRef,
)

HEADER = "# Code generated by dagger. DO NOT EDIT.\n"


def write_entrypoint(
    desc: ModuleDescription,
    *,
    name: str,
    output: pathlib.Path,
) -> None:
    """Write types.dang and main.dang for the module."""
    output.mkdir(parents=True, exist_ok=True)
    (output / "types.dang").write_text(render_types(desc))
    (output / "main.dang").write_text(render_main(name))


def render_types(desc: ModuleDescription) -> str:
    lines = [HEADER, "type ModuleTypes {", "  pub all: [TypeDef!]! {", "    ["]
    for obj in desc.objects:
        lines += _indent(_object(obj), 6)
        lines[-1] += ","
    for enum in desc.enums:
        lines += _indent(_enum(enum), 6)
        lines[-1] += ","
    lines += ["    ]", "  }", "}", ""]
    return "\n".join(lines)


def render_main(name: str) -> str:
    return MAIN_TEMPLATE.format(header=HEADER, name=_quote(name))


def _object(obj: ObjectDescription) -> list[str]:
    description = _opt("description", obj.description)
    if obj.interface:
        head = f"typeDef.withInterface({_quote(obj.name)}{description})"
    else:
        deprecated = _opt("deprecated", obj.deprecated)
        head = f"typeDef.withObject({_quote(obj.name)}{description}{deprecated})"
    lines = [head]
    lines.extend(
        f".withField({_quote(field.name)}, {_type(field.type)}"
        f"{_opt('description', field.description)}"
        f"{_opt('deprecated', field.deprecated)})"
        for field in obj.fields
    )
    for func in obj.functions:
        lines += _wrap("withFunction", _function(func))
    if obj.constructor is not None:
        lines += _wrap("withConstructor", _function(obj.constructor))
    return lines


def _function(func: FunctionDescription) -> list[str]:
    lines = [f"function({_quote(func.name)}, {_type(func.returns)})"]
    if func.description:
        lines.append(f".withDescription({_quote(func.description)})")
    if func.cache is not None:
        lines.append(f".withCachePolicy({_cache_policy(func.cache)})")
    if func.deprecated:
        lines.append(f".withDeprecated(reason: {_quote(func.deprecated)})")
    for flag, call in (
        (func.check, "withCheck"),
        (func.generator, "withGenerator"),
        (func.service, "withUp"),
        (func.agent, "withAgent"),
    ):
        if flag:
            lines.append(f".{call}")
    lines += [_argument(arg) for arg in func.args]
    return lines


def _cache_policy(cache: str) -> str:
    match cache:
        case "never":
            return "FunctionCachePolicy.Never"
        case "session":
            return "FunctionCachePolicy.PerSession"
        case _:
            return f"FunctionCachePolicy.Default, timeToLive: {_quote(cache)}"


def _argument(arg: ArgumentDescription) -> str:
    type_expr = _type(arg.type)
    if arg.nullable:
        type_expr += ".withOptional(true)"
    default = ""
    if arg.default_value is not None:
        default = f", defaultValue: ({_quote(arg.default_value)} :: Dagger.JSON!)"
    ignore = ""
    if arg.ignore is not None:
        ignore = f", ignore: [{', '.join(_quote(p) for p in arg.ignore)}]"
    return (
        f".withArg({_quote(arg.name)}, {type_expr}"
        f"{_opt('description', arg.description)}{default}"
        f"{_opt('defaultPath', arg.default_path)}"
        f"{_opt('defaultAddress', arg.default_address)}{ignore}"
        f"{_opt('deprecated', arg.deprecated)})"
    )


def _enum(enum: EnumDescription) -> list[str]:
    lines = [
        f"typeDef.withEnum({_quote(enum.name)}{_opt('description', enum.description)})"
    ]
    lines += [
        f".withEnumMember({_quote(m.name)}, value: {_quote(m.value)}"
        f"{_opt('description', m.description)}{_opt('deprecated', m.deprecated)})"
        for m in enum.members
    ]
    return lines


def _type(ref: TypeRef) -> str:
    expr = "typeDef"
    if ref.optional:
        expr += ".withOptional(true)"
    match ref.kind:
        case "LIST_KIND":
            assert ref.elem is not None
            return f"{expr}.withListOf({_type(ref.elem)})"
        case "ENUM_KIND":
            described = f"{_quote(ref.name)}{_opt('description', ref.description)}"
            return f"{expr}.withEnum({described})"
        case "SCALAR_KIND":
            described = f"{_quote(ref.name)}{_opt('description', ref.description)}"
            return f"{expr}.withScalar({described})"
        case "INTERFACE_KIND":
            return f"{expr}.withInterface({_quote(ref.name)})"
        case "OBJECT_KIND":
            return f"{expr}.withObject({_quote(ref.name)})"
        case _:
            return f"{expr}.withKind(TypeDefKind.{ref.kind})"


def _opt(arg: str, value: str | None) -> str:
    """A named string argument, omitted when there is nothing to say."""
    return f", {arg}: {_quote(value)}" if value else ""


def _quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _wrap(call: str, body: list[str]) -> Iterator[str]:
    yield f".{call}("
    yield from _indent(body, 2)
    yield ")"


def _indent(lines: list[str], width: int) -> list[str]:
    pad = " " * width
    return [pad + line if i == 0 else pad + "  " + line for i, line in enumerate(lines)]


MAIN_TEMPLATE = """{header}
type Entrypoint implements ModuleEntrypoint {{
  let moduleName: String! = {name}

  pub types(workspace: Workspace!): [TypeDef!]! {{
    ModuleTypes().all
  }}

  pub call(
    workspace: Workspace!,
    receiverType: String!,
    receiverValue: JSON,
    fnName: String!,
    fnArgs: JSON!,
    callDigest: String,
  ): JSON! {{
    let request = JSON.encode({{{{
      receiverType: receiverType,
      receiverValue: receiverValue,
      fnName: fnName,
      fnArgs: fnArgs,
    }}}})
    let result = runtime
      # The exec is cached on its own recipe, which holds neither the call's
      # arguments nor its cache policy; the engine's digest of the call does
      # (dagger/dagger#14491), so a policy reaches the exec through it.
      .withEnvVariable("DAGGER_MODULE_CALL_DIGEST", callDigest ?? "")
      .withExec(["python", "-m", "dagger.mod", "call", "--output", "/dagger/result.json"], stdin: request, experimentalPrivilegedNesting: true)
      .file("/dagger/result.json")
      .contents
    (result :: JSON!)
  }}

  # The module's own source, not the workspace the engine hands over: that is
  # the caller's, which holds the module only when the module sits in it.
  let runtime: Container! {{
    PythonModuleBuild(
      contextDir: directory.withDirectory(".", currentModule.source, exclude: ["**/.venv", "**/__pycache__"]),
      subPath: ".",
      moduleName: moduleName,
    ).installed
  }}
}}
"""
