name: "releaser release"
description: "Runs releaser release function on a project"

inputs:
  dagger_cloud_token:
    required: true
    description: "Dagger cloud token"
  shiryu_version:
    required: false
    description: "Shiryu version"
    default: "feat/add-python-sdk-release"
  sdk_language:
    description: "SDK programming language"
    default: "python"
  auth_token:
    description: "Authorization token"
  platform:
    description: "Platform config OS and architecture in a Container"
    default: "linux/amd64"
  project_directory:
    description: "Project directory path."
    default: "."
  vcs_user_email:
    description: "VCS user email"
    default: "ci@shiryu.dev"
  vcs_user_name:
    description: "VCS user name"
    default: "CI Release Bot"

runs:
  using: "composite"
  steps:
    - id: call_dagger_releaser_release
      name: Call Dagger Releaser release
      uses: dagger/dagger-for-github@v8.4.0
      env:
        AUTH_TOKEN: "${{ inputs.auth_token }}"
      with:
        version: "v0.21.7"
        verb: call
        module: github.com/fvonbergen/shiryu@${{ inputs.shiryu_version }}
        args: ${{ inputs.sdk_language }} releaser release --auth-token=env://AUTH_TOKEN --platform="${{ inputs.platform }}" --project-directory="${{ inputs.project_directory }}" --vcs-user-email="${{ inputs.vcs_user_email }}" --vcs-user-name="${{ inputs.vcs_user_name }}"
        cloud-token: ${{ inputs.dagger_cloud_token }}
