name: quality
on: push

env:
  DO_NOT_TRACK: "1"

jobs:
  auditor_audit:
    name: Auditor audit
    runs-on: ubuntu-latest
    steps:
      - id: check_out_code
        name: Check out code
        uses: actions/checkout@v7
      - id: auditor_audit
        name: Auditor audit
        uses: "./.github/actions/auditor_audit"
        with:
          dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          shiryu_version: "feat/add-python-sdk"
          sdk_language: "python"
          platform: "linux/amd64"
          project_directory: "."
  builder_test:
    name: Builder test
    runs-on: ubuntu-latest
    steps:
      - id: check_out_code
        name: Check out code
        uses: actions/checkout@v7
      - id: builder_test
        name: Builder test
        uses: "./.github/actions/builder_test"
        with:
          dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          shiryu_version: "feat/add-python-sdk"
          sdk_language: "python"
          platform: "linux/amd64"
          project_directory: "."
  checker_check:
    name: Checker check
    runs-on: ubuntu-latest
    steps:
      - id: check_out_code
        name: Check out code
        uses: actions/checkout@v7
      - id: checker_check
        name: Checker check
        uses: "./.github/actions/checker_check"
        with:
          dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          shiryu_version: "feat/add-python-sdk"
          sdk_language: "python"
          platform: "linux/amd64"
          project_directory: "."
  documenter_document:
    name: Documenter document
    runs-on: ubuntu-latest
    steps:
      - id: check_out_code
        name: Check out code
        uses: actions/checkout@v7
      - id: documenter_document
        name: Documenter document
        uses: "./.github/actions/documenter_document"
        with:
          dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          shiryu_version: "feat/add-python-sdk"
          sdk_language: "python"
          platform: "linux/amd64"
          project_directory: "."
  linter_lint_code:
    name: Linter lint_code
    runs-on: ubuntu-latest
    steps:
      - id: check_out_code
        name: Check out code
        uses: actions/checkout@v7
      - id: linter_lint_code
        name: Linter lint_code
        uses: "./.github/actions/linter_lint_code"
        with:
          dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          shiryu_version: "feat/add-python-sdk"
          sdk_language: "python"
          platform: "linux/amd64"
          project_directory: "."
  linter_lint_vcs:
    name: Linter lint_vcs
    runs-on: ubuntu-latest
    steps:
      - id: check_out_code
        name: Check out code
        uses: actions/checkout@v7
      - id: linter_lint_vcs
        name: Linter lint_vcs
        uses: "./.github/actions/linter_lint_vcs"
        with:
          dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          shiryu_version: "feat/add-python-sdk"
          sdk_language: "python"
          branch_history: "True"
          platform: "linux/amd64"
          project_directory: "."
  tester_unit:
    name: Tester unit
    runs-on: ubuntu-latest
    steps:
      - id: check_out_code
        name: Check out code
        uses: actions/checkout@v7
      - id: tester_unit
        name: Tester unit
        uses: "./.github/actions/tester_unit"
        with:
          dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          shiryu_version: "feat/add-python-sdk"
          sdk_language: "python"
          platform: "linux/amd64"
          privileged_nesting: "False"
          project_directory: "."